gpu_id: "0"
save_model_name: "ddpg_ctm2_exp1"
ddpg:
  total_timesteps: 4000000
  gamma: 0.99
  memory_policy: # None
  eval_env: # None
  nb_train_steps: 200
  nb_rollout_steps: 100
  nb_eval_steps: 100
  param_noise:
    initial_stddev: 0.1
    desired_action_stddev: 0.1
    adoption_coefficient: 1.01
  action_noise:
    mean: 0
    sigma: 0
  normalize_observations: False
  tau: 0.001
  batch_size: 128
  param_noise_adaption_interval: 50
  normalize_returns: False
  enable_popart: False
  observation_range: (-5.0, 5.0)
  critic_l2_reg: 0.0
  return_range: (-inf, inf)
  actor_lr: 0.0001
  critic_lr: 0.001
  clip_norm: # None
  reward_scale: 1.0
  render: False
  render_eval: False
  memory_limit: 100
  verbose: 1
  tensorboard_log: # None
  _init_setup_model: True
  policy_kwargs: # None
  full_tensorboard_log: False
